import { StyleSheet } from "react-native";

export const styles = StyleSheet.create({
    container: {
        flex: 1,
        backgroundColor: "#f8fafc",
        padding: 18,
    },
    navbar: {
        flexDirection: "row",
        alignItems: "center",
        gap: 12,
        marginTop: 12,
        marginBottom: 25,
    },
    logoBox: {
        width: 42,
        height: 42,
        borderRadius: 12,
        backgroundColor: "#2563eb",
        justifyContent: "center",
        alignItems: "center",
    },
    logoText: {
        fontSize: 24,
        fontWeight: "800",
        color: "#111827",
    },
    hero: {
        backgroundColor: "#ffffff",
        borderRadius: 26,
        padding: 26,
        alignItems: "center",
        shadowColor: "#000",
        shadowOpacity: 0.06,
        shadowRadius: 14,
        elevation: 4,
    },
    eyebrow: {
        color: "#2563eb",
        fontWeight: "800",
        marginBottom: 14,
    },
    title: {
        fontSize: 42,
        fontWeight: "900",
        color: "#111827",
        textAlign: "center",
        lineHeight: 50,
    },
    blueText: {
        color: "#2563eb",
    },
    subtitle: {
        color: "#5b6472",
        textAlign: "center",
        lineHeight: 22,
        marginTop: 18,
        marginBottom: 28,
    },
    mainButton: {
        width: "100%",
        backgroundColor: "#2563eb",
        paddingVertical: 15,
        borderRadius: 15,
        alignItems: "center",
    },
    mainButtonText: {
        color: "#ffffff",
        fontWeight: "800",
        fontSize: 16,
    },
    statsRow: {
        flexDirection: "row",
        gap: 10,
        marginTop: 18,
    },
    statCard: {
        flex: 1,
        backgroundColor: "#ffffff",
        borderRadius: 18,
        padding: 14,
        alignItems: "center",
        borderWidth: 1,
        borderColor: "#e5e7eb",
    },
    statNumber: {
        fontSize: 24,
        fontWeight: "900",
        color: "#111827",
        marginTop: 8,
    },
    statLabel: {
        color: "#6b7280",
        fontSize: 12,
        fontWeight: "700",
        marginTop: 4,
    },
    sectionCard: {
        backgroundColor: "#ffffff",
        borderRadius: 22,
        padding: 20,
        marginTop: 18,
        borderWidth: 1,
        borderColor: "#e5e7eb",
    },
    sectionTitle: {
        fontSize: 22,
        fontWeight: "900",
        color: "#111827",
        marginBottom: 16,
    },
    emptyText: {
        color: "#6b7280",
        textAlign: "center",
    },
    jobPreview: {
        flexDirection: "row",
        alignItems: "center",
        gap: 12,
        padding: 14,
        borderWidth: 1,
        borderColor: "#e5e7eb",
        borderRadius: 16,
        marginBottom: 12,
        backgroundColor: "#fbfdff",
    },
    jobIcon: {
        width: 42,
        height: 42,
        borderRadius: 12,
        backgroundColor: "#eff6ff",
        justifyContent: "center",
        alignItems: "center",
    },
    jobInfo: {
        flex: 1,
    },
    jobTitle: {
        fontWeight: "800",
        color: "#111827",
    },
    jobCompany: {
        color: "#6b7280",
        marginTop: 3,
        fontSize: 13,
    },
    jobType: {
        backgroundColor: "#f3f4f6",
        color: "#374151",
        paddingVertical: 7,
        paddingHorizontal: 10,
        borderRadius: 999,
        fontSize: 11,
        fontWeight: "800",
    },
    aboutCard: {
        backgroundColor: "#ffffff",
        borderRadius: 22,
        padding: 20,
        marginTop: 18,
        marginBottom: 30,
        borderWidth: 1,
        borderColor: "#e5e7eb",
    },
    aboutText: {
        color: "#6b7280",
        lineHeight: 22,
    },
    categoryText: {
        marginTop: 16,
        color: "#2563eb",
        fontWeight: "800",
    },
});